/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarFace: typeof import('./src/components/shared/AvatarFace.vue')['default']
    ConfirmModal: typeof import('./src/components/shared/ConfirmModal.vue')['default']
    CrashScreen: typeof import('./src/components/shared/CrashScreen.vue')['default']
    EmptyState: typeof import('./src/components/shared/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./src/components/shared/ErrorBoundary.vue')['default']
    FlickeringGrid: typeof import('./src/components/shared/FlickeringGrid.vue')['default']
    FramedModal: typeof import('./src/components/shared/FramedModal.vue')['default']
    GridBackdrop: typeof import('./src/components/shared/GridBackdrop.vue')['default']
    NotFound: typeof import('./src/components/shared/NotFound.vue')['default']
    PageSkeleton: typeof import('./src/components/shared/PageSkeleton.vue')['default']
    PuffMood: typeof import('./src/components/shared/PuffMood.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlowNotice: typeof import('./src/components/shared/SlowNotice.vue')['default']
    StatusScreen: typeof import('./src/components/shared/StatusScreen.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.3_de397ad76e20793deab18f55a42a56ba/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.3_de397ad76e20793deab18f55a42a56ba/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCommandPalette: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.3_de397ad76e20793deab18f55a42a56ba/node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.3_de397ad76e20793deab18f55a42a56ba/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.3_de397ad76e20793deab18f55a42a56ba/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.3_de397ad76e20793deab18f55a42a56ba/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.3_de397ad76e20793deab18f55a42a56ba/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
